In [2]:
import numpy as np
a = np.empty(4, dtype = int)
print(a)


[0 0 0 0]


In [3]:
a=np.random.randint(1, 4)
print(a)

3


In [10]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
a=[1, 2, 3,4,5,6,3,2,3,1,2]
a=np.array(a)
b,s=np.unique(a,return_counts=True)
print(b)
print(s)
ind=np.argmax(s)
print(ind)


[1 2 3 4 5 6]
[2 3 3 1 1 1]
1


In [20]:
import numpy as np
a= [[21,20,19,18,17]
  ,[16,15,14,13,12]
  ,[11,10,9,8,7]
  ,[6,5,4,3,2]]
a=np.array(a)
a

array([[21, 20, 19, 18, 17],
       [16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2]])